[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
  | migrations
  | env
  | \.git
  | static
)/
'''

[tool.isort]
multi_line_output = 3
line_length = 120
skip = 'migrations'
include_trailing_comma = true
